sudo: false
language: php
env:
  global:
      - DEFAULT_COMPOSER_FLAGS="--prefer-dist --no-interaction --no-progress --optimize-autoloader"
php:
  - 7.2
  - 7.3
services:
  - mysql
  - postgresql
cache:
  directories:
    - vendor
    - $HOME/.composer/cache
matrix:
  fast_finish: true
  include:
    - php: "7.2"
    - php: "7.3"
    - php: nightly

  allow_failures:
    - php: nightly

before_install:
  - phpenv config-rm xdebug.ini || echo "xdebug is not installed"
#  - mysql --version

# initialize database
install:
  - travis_retry composer self-update
  - travis_retry composer global require hirak/prestissimo
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - travis_retry composer install $DEFAULT_COMPOSER_FLAGS
before_script:
  - php --version
  - composer --version
#prepare statement for later
#  - mysql -e 'CREATE DATABASE `yii2-message`;';
#prepare migrations here
after_script:
  - travis_retry wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover

script:
- vendor/bin/codecept run $CODECEPTION_FLAGS


